services:
  nginx:
    image: ${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl_data/letsencrypt:/app/ssl/letsencrypt:ro # ssl 인증서