name: Nginx CD

on:
  push:
    branches:
      - main    # 운영
      - release # 스테이징
      - develop # 개발

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'release' && 'stage' || github.ref_name == 'develop' && 'dev' }}
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v5
      
      - name: SSH 키 준비하기
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2-ssh-private-key.pem
          chmod 600 ~/.ssh/ec2-ssh-private-key.pem
          ssh-keyscan -H ${{ secrets.EC2_SERVER_HOST }} >> ~/.ssh/known_hosts

      # 1. .env 파일 생성
      - name: 환경변수 파일(.env) 만들기
        run: |
          cat <<EOF > .env
          # 이미지 정보
          NGINX_IMG_NAME=${{ vars.NGINX_IMG_NAME }}
          NGINX_IMG_TAG=${{ vars.NGINX_IMG_TAG }}
          
          # 도메인 정보
          DOMAIN=${{ vars.DOMAIN }}
          
          # 프록시 대상 주소 (Secrets에 있는 Private IP 사용)
          WS_HOST=${{ secrets.WS_HOST }}
          WS_PORT=${{ vars.WS_PORT }}
          API_SERVER_HOST=${{ secrets.API_SERVER_HOST }}
          API_SERVER_PORT=${{ vars.API_SERVER_PORT }}
          EOF

      # 2. 파일 전송 (템플릿 파일 꼭 보내야 함)
      - name: 배포 파일들 EC2로 보내기
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} "mkdir -p /home/${{ vars.EC2_SERVER_USER }}/app/nginx"
          scp -i ~/.ssh/ec2-ssh-private-key.pem docker-compose.yml .env nginx.conf.template ${{ vars.EC2_SERVER_USER  }}@${{ secrets.EC2_SERVER_HOST }}:/home/${{ vars.EC2_SERVER_USER }}/app/nginx/

      - name: 도커 설치되어 있나 확인
        id: check-docker
        run: |
          DOCKER_EXISTS=$(ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} 'command -v docker >/dev/null && echo "true" || echo "false"')
          echo "docker_exists=$DOCKER_EXISTS" >> $GITHUB_OUTPUT

      - name: 도커 없으면 설치하기
        if: steps.check-docker.outputs.docker_exists == 'false'
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} << 'EOF'
              sudo apt-get update
              sudo apt-get install -y \
                  ca-certificates \
                  curl \
                  gnupg \
                  lsb-release
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
                | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
                https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" \
                | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
              sudo usermod -aG docker $USER
          EOF

      # 3. 배포 실행
      - name: 도커 컴포즈로 배포 시작
        run: |
          ssh -i ~/.ssh/ec2-ssh-private-key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_SERVER_USER }}@${{ secrets.EC2_SERVER_HOST }} << EOF
              cd ~/app/nginx
              docker compose down
              docker compose pull
              docker compose up -d
              docker image prune -f
          EOF

# [설정 가이드]
# 1. Secrets
# - WS_HOST, API_SERVER_HOST
# - EC2_SSH_PRIVATE_KEY, EC2_SERVER_HOST
#
# 2. Variables
# - DOMAIN (예: example.com)
# - NGINX_IMG_NAME, NGINX_IMG_TAG
# - WS_PORT, API_SERVER_PORT
# - EC2_SERVER_USER
